apiVersion: v1
kind: ConfigMap
metadata:
  name: tasky-env-config
data:
  .env: |
    APP_PORT=8000
    DB_HOST=192.168.1.9
    DB_USERNAME=root
    DB_PASSWORD=123456
    DB_PORT=27017
    DB_NAME=tasky_db